CREATE TABLE Livro
(
	Id INT NOT NULL,
	Titulo VARCHAR(150) NOT NULL,
	Imagem VARCHAR(200) NOT NULL,
	Descricao VARCHAR(200),
	Id_Usuario INT NOT NULL,
	PRIMARY KEY (Id)
	FOREIGN KEY (Id) REFERNCES Usuario(Id)
);

CREATE TABLE Usuario
(

	Id INT NOT NULL,
	Nome VARCHAR(150) NOT NULL,
	Senha VARCHAR(150) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Data_nasc DATE NOT NULL,
	PRIMARY KEY(Id)

);
