CREATE DATABASE Zeus;
USE Zeus;

CREATE TABLE Livro
(
	Id INT(11) NOT NULL AUTO_INCREMENT,
	Titulo VARCHAR(150) NOT NULL,
	Imagem VARCHAR(200) NOT NULL,
	Descricao TEXT,
	Id_Usuario INT NOT NULL,
	PRIMARY KEY (Id)
	FOREIGN KEY (Id) REFERENCES Usuario(Id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS Usuario
(

	Id INT(11) NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(150) NOT NULL,
	Senha VARCHAR(150) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Data_nasc DATE NOT NULL,
	PRIMARY KEY(Id)

) ENGINE=InnoDB  DEFAULT CHARSET=latin1;
