CREATE TABLE Livro
(
	Id INT NULL,
	Titulo VARCHAR(150) NOT NULL,
	Descricao VARCHAR(200) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE Pessoa
(

	Id INT NULL,
	Nome VARCHAR(150) NOT NULL,
	Senha VARCHAR(150) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Data_nasc DATE NOT NULL,
	PRIMARY KEY(Id)

);
CREATE TABLE Adiciona
(
	Id INT NULL,
	Id INT NULL,
	PRIMARY KEY (Id, Id),
	FOREIGN KEY (Id) REFERENCES Livro(Id),
	FOREIGN KEY (Id) REFERENCES Pessoa(Id)
);
